### ISSUE TITLE
Roadmap to V1

### ISSUE THREAD

**Issue by Strongleong** [Strongleong/Paintle#9]
- [X] Searching for correct words to input into wordle
 - [X] Language selection (some regions of the world have their own wordle)
 - [x] Uploading your own wordle dictionary (#4) 
 - [x] Night/day scheme switching (#5)
 - [x] Colorblind mode color scheme (#6)
 - [x] Some animations (#7)
 - [x] Board reset (#8)
